- api/statistics.js
- components/_pages/index/CounterCardLoader.vue
- components/_pages/index/DataSummary.vue
- components/_pages/index/StatisticLoader.vue
- nuxt.config.js
- plugins/initial-data.js
- plugins/vuex-router-sync.js
- store/banners.js
- store/faqs.js
- store/infographics.js
- store/news.js
- store/statistics.js
> fix #15: Pindahkan sumber data harian di homepage ke firebase

- api/infographic.js
- components/Appbar/index.vue
- components/ShareableItems/ShareableItem.vue
- components/ShareableItems/index.vue
- pages/ShareableItems/ShareableItem.vue
- pages/ShareableItems/index.vue
- pages/index.vue
- pages/infographics/_slug.vue
- pages/infographics/index.vue
note:
- tombol unduh hanya membuka public url di tab baru, karena bucket belum di set untuk direct download (terhalang CORS)
- tombol share saat ini direct ke whatsapp
> feat: info praktikal

- pages/index.vue
somehow, <a :href> prop isnt bound to computed property @_@
> fix: link to prixa

- pages/index.vue
> fix: remove redundant call center section

- pages/index.vue
- store/remote-config.js
> fix: bind anchor href to remote config

- api/news.js
- components/ArticleList.vue
- lib/metainfo.js
- nuxt.config.js
- pages/articles/_slug.vue
- pages/articles/index.vue
- pages/contact/index.vue
- pages/index.vue
- pages/infographics/_slug.vue
- pages/infographics/index.vue
> feat: add meta info (opengraph, twitter)

- components/ImageCarousel/index.vue
- pages/index.vue
> feat: carousel banners

- components/CallCard/index.vue
- components/ImageCarousel/index.vue
- pages/index.vue
> fix: samakan banners ratio dengan mobile app

- components/BarStat/index.vue
- components/BarStatArea/index.vue
- components/BarStatDetail/index.vue
- components/BarStatHarianAkumulatif/index.vue
- components/BarStatJenisKelamin/index.vue
- components/BarStatTable/index.vue
- components/BarStatUsia/index.vue
- components/MapSebaranCovid/index.vue
- components/SortableDatatable/index.vue
- components/_pages/index/DataSummary.vue
- components/_pages/index/StatisticLoader.vue
- pages/data/index.vue
@akatgelar 
@yunusffz
notes:
- MDB-Datatable sudah dihapus, digantikan dengan native <table> element, dengan fungsi sorting dan config yang sama dengan MDB-Datatable
- Bootstrap sudah dimigrasikan ke Tailwind, kecuali untuk komponen MapSebaranCovid dan MapFaskes
> chore: migrate /data components to tailwind css

- nuxt.config.js
- pages/index.vue
> chore: minor renaming

- api/banner.js
- components/ImageCarousel/index.vue
> feat: add carousel navigation buttons

- components/SponsorList/index.vue
- components/TopAlert/index.vue
- components/_pages/index/DataTabs.vue
- pages/index.vue
- store/remote-config.js
resolve #82 , #81 , #80 
edited:
resolve #84
> feat (homepage): add relawan covid backlink, make data tabs scrollable, add section image

- api/task-force.js
- components/TaskForce/index.vue
- pages/contact/index.vue
- store/task-forces.js
implement feature #94 
cc: @adrianpdm  @yohang88
> Add task force contact list

- assets/content/test-result/footer.html
- assets/content/test-result/inconclusive.html
- assets/content/test-result/negative.html
- assets/content/test-result/non-reactive.html
- assets/content/test-result/positive.html
- assets/content/test-result/reactive.html
- nuxt.config.js
- package-lock.json
- package.json
- pages/temp/result/_id.vue
langsung ke master karena hotfix
> Chore: update test result HTML Content

- assets/stylesheet/main.scss
- components/Blog/AnchorPostPreview.vue
- components/Blog/BlogPostPreview.vue
- components/LatestUpdateList.vue
> style: update CSS for national/world news

- components/_pages/index/DataSummary.vue
- components/_pages/index/StatisticLoader.vue
- lib/number.js
- nuxt.config.js
- package-lock.json
- package.json
- pages/index.vue
- plugins/numbro.js
> feat: add numerical data formatter

- components/Blog/AnchorPostPreview.vue
> fix: article backlink

- lib/slugify.js
- pages/temp/disclaimer/rdt.vue
> feat: add RDT disclaimer page

- components/BarStatTable/index.vue
- components/MapV2SebaranCluster/index.vue
- components/MapV2SebaranFaskes/index.vue
- components/MapV2SebaranPolygon/index.vue
- components/SortableDatatable/index.vue
change sort with select option,
remove No
> fix: change sort default,

- api/donation.js
- assets/stylesheet/main.scss
- components/Appbar/index.vue
- components/_pages/donate/LogisticTable.vue
- components/_pages/donate/ParticipationForm.vue
- pages/donate/logistic.vue
- store/donate.js
sorry, ga ngeuh kalo backlog form dengan table non-tunai ternyata terpisah. kirain disatukan :D wkwkwk... udah coba dibikin improvement sekalian utk form beserta multiple select table logistik item nya ... monggo di kroscek dlu aja kang ... kurang nya nanti tinggal dimodifikasi, karena masih ada miss di api terkait parameter yg blm lengkap sama API query search dan where
> fix: improvement donate non tunai (table & form)

- pages/index.vue
> feat: backlink to indorelawan

- components/_pages/donate/LogisticTable.vue
Request kang firman, hide column terpenuhi karena belum ada data sebenarnya.
> fix: hide column terpenuhi

- api/donation.js
- components/DataPCR/index.vue
- components/_pages/donate/LogisticTable.vue
- pages/donate/index.vue
- pages/donate/logistic.vue
[Web Donasi]
- Hide column terpenuhi https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/pull/184
- Fix table view and API params https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/pull/185
> Merge "development" into "master"

- components/_pages/donate/KPBMContact.vue
> fix: hotline donasi

- components/_pages/donate/ParticipationForm.vue
update bugs di halaman donasi non tunai pada saat user klik submit kirim
> Fix: Submit donasi non tunai

- pages/privacy/index.vue
- store/remote-config.js
Setup `/privacy` page views for privacy policy information.
> Add page views for privacy policy

- components/BarStatAreaSingleV2/index.vue
- components/BarStatHarianAkumulatifV2/index.vue
- components/BarStatJenisKelamin/index.vue
- components/BarStatUsia/index.vue
- components/ConfirmedCaseList/index.vue
- components/DataPCR/index.vue
- components/DataRDT/index.vue
- components/MapSebaranCovid/index.vue
- components/MapSebaranHeatmap/index.vue
- components/MapV2SebaranTimeslider/index.vue
- components/MapV3SebaranTitik/index.vue
- components/UnderInvestigationCaseList/index.vue
- components/UnderMonitoringCaseList/index.vue
- components/_pages/index/DataSummary.vue
- components/_pages/index/StatisticLoader.vue
- pages/data/index.vue
- pages/distribution-case/index.vue
- pages/index.vue
- store/data-kasus-gender.js
- store/data-kasus-harian-kota.js
- store/data-kasus-harian.js
- store/data-kasus-total.js
- store/data-kasus-umur.js
- store/data-sebaran-marker.js
1. data summary --> angka jabar, angka pertumbuhan harian
2. data summary odp / pdp --> tambah odp / pdp meninggal
3. data summary odp / pdp --> change loading skeleton
4. chart gender  --> change API
5. chart usia --> change API
6. map --> change API
> Change old API to new dynamic API

- api/donation.js
- components/_pages/donate/LogisticTable.vue
move data source from API logistik to Firebase
> feat: move logistic donation table data source to firebase

- components/PopupCampaign/index.vue
- Size can be set in pixel units from remote config
- Maximum popup size is 80% viewport width, 80% viewport height, whatever comes first
> [hotfix] CampaignPopup: size can be set from remote config; maximum size is set to 80% screen size;

- .gitignore
- README.md
- package.json
- script/firestore-export.js
Add a command line to export Firestore collection to json file.
```
npm run export collection-name
```
> feat: export firestore collection to json

- pages/index.vue
> HomepageContent: revamp

- api/infographic.js
- pages/info/infographics/index.vue
- store/infographics.js
Use cursor + vuex cache for paginated infographics list
> Infographics: use cursor for infographics pagination

- components/_pages/donate/FundParticipationForm.vue
- components/_pages/donate/ParticipationForm.vue
Ensure document counters/donation and counters/donation-cash is incremented on post document.
> Use firebase transaction to increment counter + save new document

- components/BarStatAreaSingleV2IstilahBaru/index.vue
- components/_pages/index/CounterCardLoader.vue
- components/_pages/index/DataTabs.vue
- pages/data/index.vue
- store/data-kasus-dwimingguan-kota-v2.js
- store/data-kasus-dwimingguan-provinsi-v2.js
- store/data-kasus-mingguan-kota-v2.js
- store/data-kasus-mingguan-provinsi-v2.js
> feat: Filter Group Waktu

- components/PopupCampaign/index.vue
- components/_pages/donate/ParticipationForm.vue
- pages/index.vue
- pages/mass-tracing.vue
Added:
- iframe to mass tracing website
Fixed:
- remove unnecessary whitespace
Merge hotfixes:
- homepage image assets
> mass-tracing iframe; minor fixes;

- components/SponsorList/index.vue
added:
- LaporCovid19.org logo and backlink
> Sponsors: add laporcovid19 logo and backlink

- components/DataRDT/index.vue
Perubahan tanggal update terakhir RDT
sebelumnya sama dengan tanggal kasus
sekarang punya tanggal sendiri
> fix: change last update RDT

- components/DataRDT/index.vue
- components/SponsorList/index.vue
Perubahan tanggal update terakhir RDT, sebelumnya sama dengan tanggal kasus, sekarang punya tanggal sendiri.
> Merge "development" into "production"

- components/AppDrawer/index.vue
- components/Appbar/desktop.vue
- pages/donate/fund.vue
modified:
- prevent access to cash donation page at `/donate/fund`;
- re-route `Donasi` menu link to `/donate/logistic`.
> prevent access to donation cash page;

- components/CloseContactCaseListIstilahBaru/index.vue
- components/ConfirmedCaseList/index.vue
- components/ConfirmedCaseListIstilahBaru/index.vue
- components/DataPCR/index.vue
- components/DataPCRIstilahBaru/index.vue
- components/DataRDT/index.vue
- components/MapV4SebaranPolygonIstilahBaru/index.vue
- components/ProbableCaseListIstilahBaru/index.vue
- components/SuspectCaseListIstilahBaru/index.vue
- components/UnconfirmedCaseList/index.vue
- components/UnderInvestigationCaseList/index.vue
- components/UnderMonitoringCaseList/index.vue
- lib/date.js
1. Penambahan fungsi pada lib date untuk format tanggal indonesia
2. Perubahan pemanggilan format date, sebelumnya pakai moment di tiap page, menjadi memanggil lib date
3. Perubahan disclaimer peta sebaran, menambahkan beberapa poin disclaimer
> Perubahan pemanggilan format date & perubahan disclaimer peta sebaran

- components/BarStatHarianAkumulatifV2IstilahBaru/index.vue
- components/MapV4SebaranPolygonIstilahBaru/index.vue
- components/_pages/index/DataSummaryIstilahBaru.vue
- add skeleton loader
- change default start date from 08-03-2020 to 08-15-2020
> chart daily & cumulative case 

- pages/vaccine/index.vue
- Add analytics event for page vaccine
@Arif9878 @adrianpdm @yoslie @maruf12 @Ibwedagama @bangunbagustapa @maulanayuseph @adtrimurdani
> Add analytics event for page vaccine

- components/CardSwiper/index.vue
- components/Vaccine/HoaxNews.vue
- components/Vaccine/NewsCard.vue
- Route to /articles on `NewsCard` item click
- Route to pre-defined backlink on `AntiHoax` item click
> Make news-card and anti-hoax clickable

- components/BorHospital/index.vue
- fix sort table bor hospital
izin preview dashboard
> fix: sorting bor hospital

- components/BarStatHarianAkumulatifV2IstilahBaru/index.vue
- components/BorAggregationCategory/CardBor.vue
distribution-healthcare: 
- Change starting point doughnut chart BOR
data:
-  Change default date "Bar Chart Harian Akumulatif"
> Dashboard - Change Default Chart

- components/BorAggregationCategory/index.vue
- pages/distribution-healthcare/index.vue
Izin Generate Preview 
- Ubah disclaimer BOR 
- Penambahan disclaimer BOR Tabel Rumah Sakit
> fix: change disclaimer BOR

- api/vaksin.js
- nuxt.config.js
- pages/vaccine/index.vue
- remove filter for items with no source
- set `/vaccine` page as CSR route
- add styling for link inside html content
> Rework "/vaccine" page

- components/AppDrawer/index.vue
- pages/vaccine/index.vue
- Add vaccine menu item on navigation drawer
- Add thin border on table element
- Make table scrollable
> Add vaccine menu item on navigation drawer

- components/_pages/index/IsolasiMandiri/PermohonanKebutuhanIsoman.vue
- components/_pages/index/IsolasiMandiri/index.vue
https://jabardigitalservice.slack.com/archives/C011EEWL19N/p1625707537006500
> Change medicine request redaction

- components/_pages/index/IsolasiMandiri/ActionCard.vue
- components/_pages/index/IsolasiMandiri/PermohonanKebutuhanIsoman.vue
- components/_pages/index/IsolasiMandiri/index.vue
https://jabardigitalservice.slack.com/archives/C011EEWL19N/p1625707537006500
> Change action card redaction

- components/AppDrawer/index.vue
- components/Appbar/desktop.vue
- pages/oxygen/index.vue
- Change page header title and header body
- Change menu title, both on desktop and mobile
> rework oxygen page title and content

- components/AppDrawer/index.vue
- components/Appbar/desktop.vue
- components/OxygenAccordion/index.vue
- pages/oxygen/index.vue
- store/oxygen.js
- Change menu, header, and subheader wording
- Add loading state on "Terapi Oksigen" content and "Agen Oksigen" list item view
> Oxygen Page: change wording, add loading state

- components/DataRDT/index.vue
data:
- Remove RDT description in statistik page
> Dashboard - Remove RDT Antibodi in statistik

- api/oxygen.js
- components/OxygenAccordion/OxygenBanner.vue
- components/OxygenAccordion/OxygenFilter.vue
- components/OxygenAccordion/OxygenListItem.vue
- components/OxygenAccordion/index.vue
- nuxt.config.js
- pages/oxygen/index.vue
- store/oxygen.js
Task: https://trello.com/c/3wwgRmfG/884-web-s4-oksigen-filtering-pencarian-agen-oksigen, https://trello.com/c/Exbdbwz2/883-web-s4-oksigen-penambahan-informasi-counter-untuk-total-agen-oksigen-saat-ini
link preview: https://deploy-preview-319--jabarprov-covid19.netlify.app/oxygen
> oxygen center banner and filter

- components/_pages/index/Tracking/EmptyResult.vue
- components/_pages/index/Tracking/TrackingResult.vue
1. Change wording
2. Verification response API adjustment
> Tracking Page Adjustment

- pages/tracking/index.vue
Add firebase analytics to Tracking Page
> Add tracking_view log event

- api/isoman.js
- components/Input/index.vue
- components/RadioButton/index.vue
- components/_pages/index/VitaminRequest/FirstStep.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
- components/_pages/index/VitaminRequest/secondStep.js
- pages/vitamin-request/index.vue
- store/isoman.js
1. Create radio button component
2. Update vuex store in isoman module
3. Create the second step of Vitamin Request Form
https://airtable.com/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec4A23pZn0mBoaO0?blocks=hide
> Second Step Request

- api/documents.js
- components/Homepage/DocumentTable/index.vue
- components/Homepage/InfographicAndDocument/index.vue
- components/SimpleTable/SimpleTable.vue
- components/SimpleTable/SimpleTableCellSkeleton.vue
- components/SimpleTable/index.js
- components/SimpleTable/index.vue
[[Web S5] Improvement Laman Landing Page](https://trello.com/c/d2VPhEcV/799-web-s5-improvement-laman-landing-page)
- Make `get` method for "document" Firebase collections accept `limit` argument
- Create SimpleTable component
- Create SimpleTable wrapper for "document" Firebase collections use case
- Insert wrapper onto InfographicAndDocument as tab content
https://user-images.githubusercontent.com/20709202/131082679-e4501d79-08b6-4f33-aec5-941238e526b8.mp4
> Create DocumentTable component for homepage design revamp

- components/FileInput/index.vue
- components/RadioButton/index.vue
- components/_pages/index/VitaminRequest/ConfirmationDetail.vue
- components/_pages/index/VitaminRequest/ConfirmationStep.vue
- components/_pages/index/VitaminRequest/FirstStep.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
- components/_pages/index/VitaminRequest/confirmationDetail.js
- components/_pages/index/VitaminRequest/firstStep.js
- components/_pages/index/VitaminRequest/secondStep.js
- nuxt.config.js
- pages/vitamin-request/index.vue
- plugins/vee-validate.js
- store/isoman.js
1. Create Confirmation Step Page
2. Store `formRequest` in vuex Store `isoman` module
3. Create File Input Component
https://airtable.com/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec8H06oIuhIqVuo0?blocks=hide
> Confirmation Step

- components/EventStatCard/EventStatCard.vue
- components/EventStatCard/EventStatCardCounter.vue
- components/EventStatCard/index.js
- components/Homepage/EventStatistics/data.example.js
- components/Homepage/EventStatistics/index.vue
- Create card view for event statistics data.
- Create grid wrapper for above cards, in accordance with UID design spec.
Figma
https://www.figma.com/file/8kS2SW7UprER6OiZvH84xz/Website-Pikobar
https://user-images.githubusercontent.com/20709202/131489974-a1814c1d-33d4-4a6b-a729-867df9b2e76e.mp4
> Create card for event statistics data

- api/isoman.js
- components/_pages/index/VitaminRequest/ConfirmationStep.vue
- components/_pages/index/VitaminRequest/firstStep.js
- components/_pages/index/VitaminRequest/secondStep.js
- store/isoman.js
1. Create `postVitaminRequest` function in `isoman` vuex module
2. Edit some input mandatory status
3. `isoman` vuex module state adjustment
https://airtable.com/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec8H06oIuhIqVuo0?blocks=hide
> Post vitamin request form

- components/BaseSkeleton/index.vue
`VueContentLoader` is now used to create skeleton view for each interface that is in loading state. Due to the difficulty/complexity in composing `VueContentLoader`, which is using SVG element like `rect` or `circle`, this base component is created to simplify skeleton creation.
BaseSkeleton shape complies with TailwindCSS css utilities.
<details>
<summary>
Light Mode
</summary>
https://user-images.githubusercontent.com/20709202/131970909-2274ac24-f7a4-4205-a1c5-81cfcce6c5c4.mp4
```vue
<template>
<BaseSkeleton class="w-16 h-16 rounded-full" />
<BaseSkeleton class="w-1/2 h-2 mb-4 rounded-full" />
<BaseSkeleton class="w-3/4 h-2 rounded-full" />
<BaseSkeleton class="w-full h-2 mb-4 rounded-full" />
<BaseSkeleton class="w-full h-2 mb-4 rounded-full" />
<BaseSkeleton class="w-full h-2 mb-4 …
```
> Create base component for skeleton view, based on TailwindCSS

- assets/stylesheet/main.scss
- components/Appbar/desktop.vue
Task:
- https://trello.com/c/d2VPhEcV/799-web-s5-improvement-laman-landing-page
Before:
After:
> adjustment header

- components/_pages/index/VitaminRequest/ConfirmationDetail.vue
Change date format from `YYYY-MM-DD` to `dddd, DD MMM YYYY`
> Change format date display

- components/Appbar/index.vue
Make AppBar elevated on window scrolled.
https://user-images.githubusercontent.com/20709202/132217797-bdf51dcc-9d13-48fc-826f-ec6e440fb05c.mp4
> Adjust AppBar elevation on scroll

- components/_pages/index/VitaminRequest/SuccessPage.vue
- components/_pages/index/VitaminRequest/firstStep.js
- components/_pages/index/VitaminRequest/secondStep.js
1. Display suggestion to screenshot receipt page for user
2. Add `.jpeg` format to file input validation rules
> Change success receipt redaction

- api/isoman.js
- components/_pages/index/Tracking/TrackingHeader.vue
- components/_pages/index/Tracking/TrackingResult.vue
1. Change tracking API url from `{host}/track` to `{host}/tracking`
2. API response language adjustment
[[TRACKING] Replace API tracking ke API yang baru](https://airtable.com/appEyAESlNjKaM4we/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/reclBhqbYMF3qW2da?blocks=hide)
> API tracking adjustment

- components/Input/index.vue
- components/_pages/index/VitaminRequest/FirstStep.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
1. Change `options` function params
2. Set max input date to today 
title: Fix input validation
participants: @ihsannaufalk @adrianpdm @maulanayuseph @Ibwedagama
> Fix input validation

- assets/icons/bubble-accent.svg
- components/Base/Jumbotron/Jumbotron.vue
- components/Base/Jumbotron/index.js
Create generic jumbotron.
***
title: Membuat tampilan jumbotron
participants: @adrianpdm
> component: create base Jumbotron component

- components/FileInput/index.vue
- components/_pages/index/VitaminRequest/firstStep.js
- components/_pages/index/VitaminRequest/secondStep.js
Preview: 
Added validation (reject) image for type `.gif`
Related:
https://airtable.com/appEyAESlNjKaM4we/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec4A23pZn0mBoaO0?blocks=hide
https://airtable.com/appEyAESlNjKaM4we/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec77qPhvg169TVCq?blocks=hide
> added validation for image type .gif

- components/Base/ActionCard/index.vue
- components/Base/ActionCardGrid/index.vue
- components/Base/Button/index.vue
- components/Base/ContentCard/index.vue
- components/Base/Section/SectionHeader.vue
- components/Homepage/EmergencyNumbers/index.vue
- Move `ContentCard` upper breakpoint to `lg`
- Fix `BaseButton` font size
- Fix gap between `SectionHeader` title and subtitle
- Replace `ActionCard` embedded button with `ContentCardButton`
- Refactor 2-column `ActionCard` grid view onto `ActionCardGrid`
- Replace `EmergencyNumbers` grid with `ActionCardGrid`
***
title: Melakukan refactor untuk komponen dasar
participants: @adrianpdm @ArifWicakSon
> Minor adjustment to some base component's styles; Refactor 2 column ActionCard grid view onto "ActionCardGrid";

- components/Appbar/desktop.vue
> active link navbar notification

- components/IgdVkAggregationCategory/CardIgdVk.vue
- components/IgdVkAggregationCategory/index.vue
- components/IgdVkHospital/index.vue
- pages/distribution-healthcare/index.vue
**Description**
- Create IGD & VK chart
- Create IGD & VK table
> Feat: Distribution health care add igd vk chart & table

- components/Vaccine/ChatAndFaq.vue
[[Web S6] [Improvement Halaman Vaksinasi] Section Berita, Hotline, FAQ](https://trello.com/c/rHAOuqZo/927-web-s6-improvement-halaman-vaksinasi-section-berita-hotline-faq)
Create action cards for chatbot and faq backlink.
***
title: Membuat backlink ke Chatbot dan FAQ Pikobar
participants: @adrianpdm @maulanayuseph @ArifWicakSon @Ibwedagama @bangunbagustapa @ihsannaufalk
> Feat: create chat and faq actions card view

- api/vaksin.js
- components/Vaccine/VaccinationSchedule.vue
- store/vaksin.js
[[Web S6] [Improvement Halaman Vaksinasi] Section Hero & Jadwal Vaksinasi](https://trello.com/c/j0JSrkXb/906-web-s6-improvement-halaman-vaksinasi-section-hero-jadwal-vaksinasi)
- Fetch airtable iframe definition from firebase
- Create table skeleton view
- Create wrapper consisting of aforementioned skeleton and iframe
https://user-images.githubusercontent.com/20709202/134626300-14c88b66-82fe-49e6-ba25-27d4dc29bedb.mp4
***
title: Embed tabel jadwal vaksinasi dari Airtable
participants: @adrianpdm @adzharamrullah @yoslie @ArifWicakSon @Ibwedagama
> Feat: vaccination schedule table view (embedded from Airtable)

- components/_pages/testimonial/index.vue
**Task Description**
when viewport mobile, section testimoni visibility automatically to be hidding
**Changes**
- add css visible on testimoni
> Fix: testimoni isoman web on viewport mobile

- components/BorAggregationCategory/index.vue
- pages/distribution-healthcare/index.vue
- fix: revert BOR tooltip description
- fix: change data BOR disclaimer
> Change BOR disclaimer & revert tooltip BOR description

- components/_pages/index/VitaminRequest/SuccessPage.vue
**Task**
[Permohonan Telekonsultasi](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwsBOcx6uSZkKxWw/recgo1zLs2mx2WJAg?blocks=hide)
**Changes**
- Add function `onclick` 
- Add `backlinks` files
**Evidence**
title: Consultation vitamin request
participants: @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank
> Feat: Consultation Vitamin Request 

- components/Appbar/desktop.vue
as described in PR title
https://trello.com/c/CRbWKvkN/961-web-s7-penambahan-akses-menu-dokumen-dan-info-praktikal
title: add infographics and documents submenu in information menu
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama
> add infographics and documents submenu in information menu

- components/AppDrawer/index.vue
- components/ArticlesPage/ListArticles.vue
- pages/faq/index.vue
- pages/index.vue
1. remove padding in `ListArticles` component
2. remove margin when faq search input filled
3. adjust `ContentCardButton` width in home page
4. add `infographics` and `documents` menu in side bar
title: Fix revamp layouting
> Fix revamp layouting

- components/_pages/index/IsolasiMandiri/backlinks.js
- components/_pages/index/IsolasiMandiri/index.vue
- components/_pages/index/VitaminRequest/SuccessPage.vue
- pages/consultation-request/index.vue
**Task**
[Consultation Request](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwsBOcx6uSZkKxWw/recgo1zLs2mx2WJAg?blocks=hide)
**Changes**
- Create `pages` consultation request
- Create a new const on `backlinks.js`
**Preview**
**Evidence**
title: Pages consultation request
participants: @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank
> Feat: Pages consultation request

- components/_pages/index/VitaminRequest/FirstStep.vue
- pages/consultation-request/index.vue
- pages/vitamin-request/index.vue
- store/isoman.js
**Related Task**
[Consultation Request](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwsBOcx6uSZkKxWw/recgo1zLs2mx2WJAg?blocks=hide)
**Changes**
- Set dynamically request type based on pages
**Evidence**
title: Dynamically request type
participants: @maulanayuseph
> Feat: Dynamically request type

- components/_pages/index/IsolasiMandiri/backlinks.js
- components/_pages/index/VitaminRequest/SuccessPage.vue
**Related Task**
[Consultation Request](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwsBOcx6uSZkKxWw/recgo1zLs2mx2WJAg?blocks=hide)
**Changes**
- Add info and detail message
- Import info and detail message to success page
**Evidence**
title: Fix wording consultation request
participants: @maulanayuseph
> Fix wording consultation request

- components/AppDrawer/index.vue
1. Restructure sidebar content
2. Make sidebar scrollable
title: Revamp sidebar
participants: @naufalihsank @maruf12 @Ibwedagama @maulanayuseph
> Revamp sidebar

- components/BorAggregationCategory/index.vue
Make fixed changes to BOR chart tooltip description (again).
title: Make fixed changes to BOR chart tooltip description (again).
participants: @hamayat @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank
> BOR chart tooltip description adjustment

- pages/contact/index.vue
https://trello.com/c/r0uEL8sp/974-web-s10-informasi-kontak-perbaikan-fungsi-pencarian
title: Fix empty image display
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @yoslie
> Fix empty image display

- pages/temp/disclaimer/rdt.vue
title: Hotfix remove button target blank
participants: @naufalihsank @Ibwedagama @bangunbagustapa @maulanayuseph
> Hotfix: remove button target _blank

- components/_pages/infographics/InfographicSkeleton.vue
- pages/info/infographics/index.vue
title: Create infographic loader
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa
> Create infographic loader

- components/_pages/index/IsolasiMandiri/index.vue
Revert backlink doctor consultation into whatsapp, related with [this](https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/commit/8364d8b9f239eb5bdee7869acff1d216d57c58e3) commit
title: Revert backlink
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa
> Hotfix: Revert backlink

- api/documents.js
- components/ImageCarousel/index.vue
- pages/info/documents/index.vue
- pages/infographics/_slug.vue
1. change `info/documents` paragraph font from `Lora` to `Roboto`
2. add extra enter in whatsapp share message
3. `Unduh` button on detail infographic page will download the current image on the carousel
title: Fix info page
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @yoslie
> Fix info page

- components/ArticlesPage/ListArticles.vue
- components/Base/TabLayout/TabItem.vue
- components/Base/TabLayout/TabLayout.vue
- pages/articles/index.vue
- store/news.js
1. implement one search for all tabs
2. display count on `TabItem` component
[[Web S10] [Informasi > Berita] Badge pada tab Jabar, Nasional, Dunia ketika menampilkan hasil pencarian](https://trello.com/c/WUkLJYIL/978-web-s10-informasi-berita-badge-pada-tab-jabar-nasional-dunia-ketika-menampilkan-hasil-pencarian)
title: Articles search improvement
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie
> Articles search improvement

- assets/stylesheet/main.scss
- pages/documents/_slug.vue
- pages/info.vue
- pages/info/documents/index.vue
- pages/info/infographics/index.vue
- store/documents.js
- store/infographics.js
1. Fix search function in `/info/infographics` and `/info/documents` pages by setting `lastSnapshot` state
2. Change some font color and family
title: Fix infographics bug
participants: @naufalihsank @adzharamrullah @Ibwedagama @bangunbagustapa
> Fix infographics bug

- pages/articles/index.vue
- pages/contact/index.vue
- pages/faq/index.vue
- pages/index.vue
- pages/info.vue
1. Change title and subtitle font family and style
2. Add backlink in vaccine content card
1. [[Web] Perbaikan Font Type](https://trello.com/c/k7r2iMvf/971-web-perbaikan-font-type)
2. [[Web S10][Landing Page] Link Selanjutnya di section Informasi Vaksin tidak mengarah ke URL vaksinasi](https://trello.com/c/mka8ng2C/993-web-s10landing-page-link-selanjutnya-di-section-informasi-vaksin-tidak-mengarah-ke-url-vaksinasi)
title: Change fonts and add backlinks
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
> Fix: Change fonts

- api/call-centers.js
- components/ContactPage/ListContact.vue
- pages/contact/index.vue
- store/call-centers.js
- store/hospitals.js
- store/task-forces.js
1. implement one search for all tabs
2. display count on tabs
[[Web S10] [Informasi > Kontak] Badge pada tab Rumah Sakit Rujukan, Call Center, Website Gugus Tugas ketika menampilkan hasil pencarian](https://trello.com/c/FP3lmqSm/982-web-s10-informasi-kontak-badge-pada-tab-rumah-sakit-rujukan-call-center-website-gugus-tugas-ketika-menampilkan-hasil-pencarian)
title: Contact search improvement
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
> Contact search improvement

- api/news.js
- pages/articles/index.vue
- store/news.js
title: Fix open article detail page
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie
> Fix: open article detail page

- components/AppFooter/index.vue
title: Change number of row in a column of footer
> Change number of row in a column of footer

- pages/info/covid-19/index.vue
title: Delete periksa diri button
> hotfix: delete periksa diri button

- assets/stylesheet/main.scss
- components/Base/Button/index.vue
- components/Base/ContentCard/ContentCardButton.vue
- components/Base/ContentCard/index.vue
- components/Base/EventStatCard/EventStatCard.vue
- components/Base/EventStatCard/EventStatCardCounter.vue
- components/Base/Section/SectionHeader.vue
- pages/index.vue
- tailwind.config.js
[[Web S12][Landing Page] Design Review - Hero, Data, Article section](https://trello.com/c/SFej2Q7h/999-web-s12landing-page-design-review-hero-data-article-section)
title: Design review landing page
> Design review landing page

- api/news.js
- components/Homepage/RecentNewsCarousel/index.vue
- components/Vaccine/NewsTabLayout.vue
title: Update recent news vaccine
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
> Insert national and world articles into recent news vaccine

- assets/stylesheet/main.scss
- components/Base/ActionCard/index.vue
- components/Base/ContentCard/index.vue
- components/Base/Jumbotron/Jumbotron.vue
- components/Base/NewsCarousel/NewsCarouselItem.vue
- components/Base/Section/SectionHeader.vue
- components/Base/TabLayout/TabItem.vue
- components/Homepage/InfographicAndDocument/index.vue
- components/Homepage/InfographicCarousel/index.vue
- components/KenaliCovid/HospitalsAndCallCenters/WrapperItem.vue
- components/Vaccine/VaccinationStages.vue
- lib/date.js
- pages/index.vue
- pages/info/infographics/index.vue
- tailwind.config.js
1. News Section (Fix styling)
2. More Info Section (Fix styling)
3. Refactor `InfographicCarousel` component
[[Web S12][Landing Page] Design Review - News, More Info section](https://trello.com/c/FyRTfVp7/1000-web-s12landing-page-design-review-news-more-info-section)
title: Design review landing page part 2
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama
> Design Review Landing Page Part 2

- api/vaksin.js
- components/Base/Alert/index.vue
- components/Base/Button/index.vue
- components/Vaccine/VaccinationScheduleFilter.vue
- components/Vaccine/VaccinationScheduleItem.vue
- pages/vaccine/schedule/index.vue
1. implement filter airtable API functionality
2. create `Alert` component
3. insert alert disclaimer message
1. [[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Filtering dan Pop up detail di Halaman Jadwal Vaksinasi](https://trello.com/c/HBJ5XbA6/1018-web-s10-vaksinasi-jadwal-vaksinasi-filtering-dan-pop-up-detail-di-halaman-jadwal-vaksinasi)
2. [[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Pembuatan Halaman Jadwal Vaksinasi menggunakan data Airtable](https://trello.com/c/LhoCRCfm/969-web-s10-vaksinasi-jadwal-vaksinasi-pembuatan-halaman-jadwal-vaksinasi-menggunakan-data-airtable)
title: Vaccine schedule filter
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @bangunbagustapa @yoslie
> Feat: Vaccine schedule filter

- components/Vaccine/VaccinationSchedule.vue
- components/Vaccine/VaccinationScheduleItem.vue
- components/Vaccine/VaccinationSchedulePopup.vue
- pages/vaccine/schedule/index.vue
1. Create `VaccinationSchedulePopup`
1. [[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Filtering dan Pop up detail di Halaman Jadwal Vaksinasi](https://trello.com/c/HBJ5XbA6/1018-web-s10-vaksinasi-jadwal-vaksinasi-filtering-dan-pop-up-detail-di-halaman-jadwal-vaksinasi)
title: Schedule Popup Detail
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @yoslie
> Schedule Popup Detail

- components/Base/Button/index.vue
- components/Vaccine/VaccinationScheduleBottomSheet.vue
- components/Vaccine/VaccinationScheduleDetail.vue
- components/Vaccine/VaccinationSchedulePopup.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/vaccine/schedule/index.vue
- plugins/vue-bottomsheet.js
1. refactor `VaccineSchedulePopup`
2. install  `@webzlodimir/vue-bottom-sheet`
3. create `VaccineScheduleDetail`
4. create `VaccineScheduleBottomSheet`
[[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Filtering dan Pop up detail di Halaman Jadwal Vaksinasi](https://trello.com/c/HBJ5XbA6/1018-web-s10-vaksinasi-jadwal-vaksinasi-filtering-dan-pop-up-detail-di-halaman-jadwal-vaksinasi)
title: Vaccine Schedule Bottomsheet
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
> Feat: Vaccine Schedule Bottomsheet

- api/vaksin.js
- components/Vaccine/VaccinationScheduleSkeleton.vue
- pages/vaccine/index.vue
- pages/vaccine/schedule/index.vue
- store/vaksin.js
1. add shimmer loading
2. fix limited vaccine schedule data (max 100 row) to unlimited
3. fix `/vaccine` hero redaction
[[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Pembuatan Halaman Jadwal Vaksinasi menggunakan data Airtable](https://trello.com/c/LhoCRCfm/969-web-s10-vaksinasi-jadwal-vaksinasi-pembuatan-halaman-jadwal-vaksinasi-menggunakan-data-airtable)
title: Improve Page Vaccine Schedule
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @yoslie
> Improve Page Vaccine Schedule

- components/Vaccine/VaccinationScheduleFilter.vue
- components/Vaccine/VaccinationScheduleItem.vue
- package-lock.json
- package.json
- pages/vaccine/schedule/index.vue
1. change date format display in `VaccinationScheduleItem`, from `YYYY-MM-DD` to `DD MMM YYYY`
2. install `vue2-datepicker`
2. add range date filter
[[Web S10] [Vaksinasi -> Jadwal Vaksinasi] Filtering dan Pop up detail di Halaman Jadwal Vaksinasi](https://trello.com/c/HBJ5XbA6/1018-web-s10-vaksinasi-jadwal-vaksinasi-filtering-dan-pop-up-detail-di-halaman-jadwal-vaksinasi)
title: add range date filter
participants: @naufalihsank @maulanayuseph @Ibwedagama @bangunbagustapa @yoslie
> Feat: add range date filter

- components/_pages/index/IsolasiMandiri/backlinks.js
- components/_pages/index/VitaminRequest/SuccessPage.vue
**Task**
[Revisi Penggantian URL pada tombol "Lanjut Konsultasi"](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/recXaffHbZrmvU5SD?blocks=hide)
**Changes**
- Change URL hotline isoman
**Evidence**
-
title: Change URL Hotline Isoman Pikobar
participants: @maulanayuseph @naufalihsank @yoslie @doohanas
> Change URL Hotline Isoman Pikobar

- components/_pages/index/IsolasiMandiri/backlinks.js
- components/_pages/index/IsolasiMandiri/index.vue
- components/_pages/index/VitaminRequest/SuccessPage.vue
- components/_pages/index/VitaminRequest/WelcomePage.vue
- pages/consultation-request/index.vue
**Task**
-
[[Web] [Revisi redaksi di halaman Selamat Datang untuk Telekonsultasi Dokter]](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/rechkCkdAYGEyJ7ao?blocks=hide)
[[Web] [Revisi Redaksi pada tombol "Tanyakan Sekarang" diganti dengan "Daftar Konsultasi" pada halaman Isoman Pikobar]](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/recqp7Vulc04q5RzV?blocks=hide)
[[Web] [Penggantian url pada tombol "Tanyakan Sekarang" menjadi: https://pikobar.jabarprov.go.id/consultation-request pada halaman Isoman Pikobar]](https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/recGdpkHv3YZSQZQj?blocks=hide)
**Changes**
-
- Change prompt `button` consultation request
- Change `URL` consultation request
- Moved redaction to …
> Feat: Improve consultation request

- components/Vaccine/VaccinationScheduleFilter.vue
title: hide datepicker temporarily
participants: @naufalihsank @yoslie @bangunbagustapa @doohanas @maulanayuseph
> hide datepicker temporarily

- components/Homepage/EventStatistics/index.vue
- components/_pages/index/VitaminRequest/ConfirmationDetail.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
- components/_pages/index/VitaminRequest/confirmationDetail.js
- store/tracking.js
**Task**
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/recL9MbcTrO0livc5?blocks=hide
https://trello.com/c/eiSnNHPF/1030-web-s14landing-page-take-down-section-kontak-erat-suspek-probable
**Changes**
**Preview**
**Evidence**
title: Improve: Shipping vitamin and check request number tracking
participants: @maulanayuseph @maruf12 @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
> Improve: Shipping vitamin and check request number tracking

- components/Homepage/EventStatistics/index.vue
- components/_pages/index/VitaminRequest/ConfirmationDetail.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
- components/_pages/index/VitaminRequest/SuccessPage.vue
- components/_pages/index/VitaminRequest/confirmationDetail.js
- components/_pages/index/VitaminRequest/firstStep.js
- store/tracking.js
**Task**
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/rec1EJwsI3yYmb7dy
https://airtable.com/appMJE57FaKQcEUwA/tbl6no9dhW3sDRJhb/viwR9haftxWJ4p6ty/recQcag65FDcun74F
**Changes**
- Add `options` select 
- Add conditional `back to menu` and title `pages`
**Evidence**
title: Fix form consultation request
participants: @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank @yoslie @doohanas
> Fix form consultation request

- components/Input/index.vue
- components/_pages/index/VitaminRequest/FirstStep.vue
- components/_pages/index/VitaminRequest/SecondStep.vue
- plugins/vee-validate.js
**Definition**
There is addition body in api `check`, Input text must be refactored to handling a new `props`.
**Changes**
- Refactor `Input` components
- Remove unused in `validate.js` file
- Emit `props` request type
**Evidence**
title: Refactor: input check nik applicant
participants: @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank @yoslie @doohanas
> Refactor: input check nik applicant

- components/Vaccine/VaccinationScheduleFilter.vue
- components/Vaccine/ageCategory.js
- pages/vaccine/schedule/index.vue
**Task**
As described on the title
**Changes**
- Change `placeholder` select
- Add new `BaseAlert` component
- Revision `ageCategory.js` list
**Evidence**
title: Add new disclaimer and revision filter list based on age
participants: @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank @yoslie @doohanas
> Add new disclaimer and revision filter list based on age

- components/Form/index.vue
- components/_pages/index/ConsultationVitamin/First.vue
- components/_pages/index/ConsultationVitamin/ProgressHeader.vue
- components/_pages/index/ConsultationVitamin/firstStep.js
- components/_pages/index/ConsultationVitamin/secondStep.js
- utils/index.js
**Changes**
- Create a validation phone number
- Adjust on change other location
- Move some function into `utils.js`
**Evidence**
title: Adjust validation identity
participants: @maulanayuseph @adzharamrullah @Ibwedagama @yoslie @doohanas
> Adjust validation identity

- components/_pages/index/ConsultationVitamin/PreviewData.vue
- components/_pages/index/ConsultationVitamin/PreviewDataDetail.vue
- components/_pages/index/ConsultationVitamin/confirmationStep.js
- components/_pages/index/ConsultationVitamin/previewData.js
- pages/consultation-request/index.vue
**Task**
[[Form Pemohon] - Hal 4 Revamp: Pratinjau Data](https://app.clickup.com/t/2nxaaz5)
**Changes**
- Create component preview data and detail
- Create list confirmation step
**Evidence**
title: Feat: Preview data consultation
participants: @maulanayuseph @bangunbagustapa @yoslie @doohanas
> Feat: Preview data consultation

- components/FileInput/index.vue
- components/Form/index.vue
- components/Input/index.vue
- components/RadioButton/index.vue
- components/SelectInput/index.vue
- components/TextArea/index.vue
- components/_pages/index/ConsultationVitamin/First.vue
- components/_pages/index/ConsultationVitamin/firstStep.js
- store/isoman.js
**Changes**
- Remove description must be filled
- Adjustment input component
- Add checkbox `applicant_name`
**Preview**
**Evidence**
title: feat: name applicant
participants: @maulanayuseph @Ibwedagama @bangunbagustapa @doohanas
> feat: name applicant

- components/Form/index.vue
- components/_pages/index/ConsultationVitamin/First.vue
- components/_pages/index/ConsultationVitamin/PreviewData.vue
- components/_pages/index/ConsultationVitamin/PreviewDataDetail.vue
- components/_pages/index/ConsultationVitamin/PreviewUpload.vue
- components/_pages/index/ConsultationVitamin/Second.vue
- components/_pages/index/ConsultationVitamin/SuccessPage.vue
- components/_pages/index/ConsultationVitamin/Third.vue
- tailwind.config.js
**Changes**
- Fix Mobile viewport upload image
- Fix State on `click` button back
- Update font `lora` page preview data
- Adjust notification validation NIK
- Add message copied to clipboard
**Evidence**
title: Fix form vitamin
participants: @maulanayuseph @Ibwedagama @bangunbagustapa @doohanas
> Fix form vitamin

- components/Vaccine/VaccinationScheduleFilter.vue
**Task**
https://app.clickup.com/t/2cy1yxq
**Changes**
- Add multiselect component
- Add new method get type vaccine
**Preview**
**Evidence**
title: feat: add filter type vaccine
participants: @maulanayuseph @Ibwedagama
> feat: add filter type vaccine

- components/Vaccine/VaccinationScheduleFilter.vue
**Task**
https://app.clickup.com/t/2cy22dt
**Changes**
- Add `Datepicker` component
**Preview**
**Evidence**
title: feat: filter based on schedule date vaccine
participants: @maulanayuseph @doohanas @Ibwedagama
> feat: filter based on schedule date vaccine

- components/BarStatAreaSingleV2IstilahBaru/BarChart.vue
- components/BarStatAreaSingleV2IstilahBaru/LineChart.vue
- components/BarStatAreaSingleV2IstilahBaru/index.vue
- components/BarStatJenisKelaminIstilahBaru/PieChart.vue
- components/BarStatJenisKelaminIstilahBaru/index.vue
- components/BarStatUsiaIstilahBaru/ButterFlyChart.vue
- components/DataPCRIstilahBaru/index.vue
- components/DataRDT/index.vue
- pages/data/index.vue
- store/data-kasus-harian-v2.js
- Data - Statistik Page
- Chart Harian
- Chart Harian Kumulatif
- Chart Jenis Kelamin
title: Change chart library forn Gchart to D3
participants:  @maulanayuseph @adzharamrullah
> Change chart library from Gchart to D3

- components/Base/Button/index.vue
- components/_pages/index/IsolasiMandiri/index.vue
- pages/isoman/index.vue
**Task**
https://app.clickup.com/t/2gp3nnq
**Changes**
- Style base `button` component
- Add `title` on section isolasi
**Preview**
**Evidence**
title: Section guide isoman
participants: @maulanayuseph @bangunbagustapa @naufalihsank @yoslie @doohanas
> Section guide isoman

- components/_pages/index/IsolasiMandiri/IsomanJumbotron.vue
**Related Task**
https://app.clickup.com/t/2gp3mtt
**Changes**
- Update redaction `subtitle` section health services
**Preview**
**Evidence**
title: Fix redaction
participants: @maulanayuseph @doohanas @Ibwedagama
> Fix wording section health services

- components/_pages/index/IsolasiMandiri/index.vue
**Related Task**
https://app.clickup.com/t/2gp3nnq
**Preview**
**Evidence**
title: Fix section guide
participants: @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank
> Fix section guide

- pages/isoman/consultation-request/index.vue
**Changes**
- Add class `container` `mx-auto`
**Preview**
Before
After
**Evidence**
title: Fix the request consultation page display container
participants: @maulanayuseph @maruf12 @Ibwedagama @agunghide @naufalihsank @yoslie @doohanas
> Fix the request consultation page display container

- pages/index.vue
**Task**
app.clickup.com/t/29p9rav
**Changes**
As described in the title
**Preview**
**Evidence**
title: Change section order on homepage
participants: @maulanayuseph @Ibwedagama @agunghide @bangunbagustapa
> Change section order on homepage

- pages/articles/index.vue
- pages/info/covid-19/index.vue
- pages/info/documents/index.vue
**Changes**
As described in the title
**Evidence**
title: Fix wording on the homepage page
participants: @maulanayuseph @Ibwedagama @agunghide @bangunbagustapa @yoslie @doohanas
> Fix wording on the homepage page

- pages/index.vue
**Changes**
As described in the title
**Preview**
title: Change info section vaccine and covid on homepage
participants: @maulanayuseph @Ibwedagama @agunghide @bangunbagustapa @yoslie
> Change info section vaccine and covid on homepage

- pages/index.vue
Changes:
- Change link dashboard data
Related Task:
https://app.clickup.com/t/2hxf83e
title: Change link dashboard data pikobar
project: Pikobar website
participants: @maruf12 @sandisunandar99
> Change link dashboard data

- app.html
Change:
- Change embeed survey jotform
Related:
https://app.clickup.com/t/2t2dapy
title: Change embeed survey jotform
participants: @maruf12 @Ibwedagama @maulanayuseph @yoslie @agunghide @sandisunandar99
> change link survey pikobar

- components/Vaccine/VaccinationScheduleFilter.vue
- components/Vaccine/typeVaccines.js
- components/_pages/index/Tracking/TrackingResult.vue
- lib/date.js
Changes:
- Add filter 'Jenis Vaksin'
Related:
https://app.clickup.com/t/3ucrgnp
title: Add filter jenis vaksin pikobar website
participants: @maruf12 @naufalihsank @yoslie @agunghide @doohanas @maulanayuseph
> Add filter 'Jenis Vaksin'

- middleware/redirect.js
- nuxt.config.js
- pages/isoman/index.vue
Changes:
- Delete section request vitamin in isoman page
- Redirect request vitamin to isoman
- Redirect page data to portal data jabar
Related:
https://app.clickup.com/t/860ph146m
title: Sunset feature request vitamin
participants: @maruf12 @naufalihsank @sandisunandar99
> Sunset feature request vitamin
