jabardigitalservice/pikobar-jabarprov-go-id

api/infographic.js, app.html, components/ShareableItems/ShareableItem.vue
note:
- typeof file extension is hardcoded in app. `next`: type must be inferred from filename / file metadata.
=> Feat: downloadable info

api/news.js, components/ArticleList.vue
Terjadi karena konversi slug hanya terjadi pada ~/api/news.js.
Sedangkan komponen [ArticleList](https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/blob/master/components/ArticleList.vue) meng-consume firebase instance secara langsung.
next:
- Buat method consume untuk flow 'Load More' pada ~/api/news.js -> [Issue #54 ](https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/issues/54)
=> temporary fix: ensure berita jabar link is clickable

components/Appbar/desktop.vue
use `<a/>` instead of `<nuxt-link/>` and handle routing manually to ensure that both internal and external link is working properly.
=> [hotfix] Appbar: replace nuxt-link with anchor to ensure external link is working properly

components/_pages/donate/FundParticipationForm.vue
include `created_at` as creation timestamp in POST data payload
=> [hotfix] CashDonation: include creation timestamp in payload

api/documents.js, components/ShareableItemTable/index.vue, lib/download-and-share-firestore-doc.js, pages/index.vue, pages/info/documents/index.vue, pages/info/infographics/index.vue, store/documents.js, store/infographics.js
Bugfixes:
- Downloaded document extension is now inferred correctly
- Document list is no longer duplicated when going from homepage `/` to documents `/info/documents`
- Infographics list is no longer duplicated when going from homepage `/` to documents `/info/infographics`
Added:
- `Load More` button on documents page `/info/documents`
=> Content: fix document and infographics pgination

components/TabLayoutV2/TabLayout.vue
Active tab marker is not properly rendered when viewport size changed at runtime.
https://user-images.githubusercontent.com/20709202/131082079-7930de86-b766-4fcd-88e7-91a4dd8bc032.mp4
Listen to viewport resize event, and update active marker accordingly.
https://user-images.githubusercontent.com/20709202/131082315-88405050-d729-41a4-85cd-51d6f194b681.mp4
=> Fix: TabLayout active tab item marker is not properly rendered when viewport size changed

components/Homepage/BannerCarousel/index.vue, components/Homepage/InfographicAndDocument/index.vue, components/Homepage/InfographicCarousel/index.vue
Create and/or adjust ImageCarousel wrapper for banners and infographics in homepage
- Rename `components/Homepage/ImageCarousel` to `components/Homepage/BannerCarousel` for better context
- Make BannerCarousel slide clickable
- Create ImageCarousel wrapper for infographics
- Insert InfographicsCarousel onto homepage tab layout
https://user-images.githubusercontent.com/20709202/131465549-740c9317-a458-4132-aa91-aed0c5811247.mp4
=> Create ImageCarousel wrapper for banners and infographics; Insert InfographicsCarousel onto tab layout;

components/Homepage/RecentNewsCarousel/index.vue, components/NewsCarousel/NewsCarousel.vue, components/NewsCarousel/NewsCarouselItem.vue, components/NewsCarousel/index.js
Carousel view previously is using VueCarousel. This PR replaced corresponding component base library with VueAwesomeSwiper, which is abstracted under `~/components/ImageCarouselV2`.
This is meant to ensure that news carousel view behaves exactly the same with infographics carousel view in homepage.
- Create carousel item view: `NewsCarouselItem`
- Create carousel view: `NewsCarousel`
- Create carousel view wrapper for recent news use case in homepage: `RecentNewsCarousel`
News carousel view in `/vaccine` route will also be replaced with `NewsCarousel` in the future.
https://user-images.githubusercontent.com/20709202/131644948-752d5774-b1fa-4225-a41d-9d45cc387e16.mp4
=> Create carousel view for news item for use in homepage

components/Base/Button/index.vue, components/ContentCard/index.vue
Button has been developed by @Arif9878  and used in `ContentCard`.
Due to similar button occurence in some routes, button is then refactored into `BaseButton`.
- Replicate embedded button within `ContentCard` into `BaseButton`.
- Replace embedded button within `ContentCard` with `BaseButton`.
- `BaseButton` supports only green color (filled or outlined), as specified in Figma.
- `BaseButton` icon can only be aligned right.
=> Refactor button into BaseButton

api/news.js, components/Base/Section/Section.vue, components/Base/Section/SectionHeader.vue, components/Homepage/EventStatistics/index.vue, components/Homepage/RecentNewsCarousel/index.vue, pages/index.vue, store/news.js
Both event statistics and recent news last update text view on above PR is still hardcoded. Also, both currently has no loading state handler. This PR address that issue.
- Add and handle loading state in section header.
- Add `getLastUpdate` XHR for firestore/articles collection
- Add `getLastUpdate` Vuex Action for vuex/news module
- Keep `lastUpdate` for both event statistics and recent news in each component state
- Expose loading state of each view using event
- Use `$refs` to access exposed `lastUpdate` value of each view on parent component (`pages/index`)
https://user-images.githubusercontent.com/20709202/132638216-04b7400e-352e-49c1-b953-707c1cc4c194.mp4
=> Add loading state for event statistics and recent news section in homepage

components/ImageCarouselV2/ImageCarousel.vue
Carousel can now bleed fully edge to-edge within a page.
Carousel is only draggable if total slide is greater than the configured slides per view.
- Carousel is configurable to responsively bleed using `swiperProps` attribute.
- Automatically compute whether dragging is allowed by comparing expected slides per view `vs` total slides length
- Refactor navigation visibility handler
https://user-images.githubusercontent.com/20709202/132795489-1f1c99d8-8919-479a-85ef-4898fb32cad5.mp4
=> ImageCarousel drag gesture and layout improvement 

components/ContentCard/ContentCardButton.vue, pages/index.vue
Previously, ContentCardButton link is always treated as an external one, by which clicking on the button will request a full page load.
This PR address the above issue.
- Ensure internal link is treated as in-app navigation (SPA).
- Ensure external link is always opened in new tab with `WindowFeatures` `noopener,noreferrer`.
- Make helper to scroll onto hash anchor, e.g `<div id="#scrollTarget" />`
- Fix infographics view backlink
https://user-images.githubusercontent.com/20709202/132809466-55d455ad-f830-494c-badd-138b4282fc54.mp4
*link to google.com is setup for previewing purpose only
https://user-images.githubusercontent.com/20709202/132809646-6cfa8ba1-9244-4212-8fbe-87b20c38bbc1.mp4
https://user-images.githubusercontent.com/20709202/132809468-ff8ffca2-d3a0-44a1-9939-3cbaaac6fa24.mp4 …
=> Fix: Handle homepage backlink navigation by detecting its link type (internal, external, hash anchor)

components/Base/ActionCard/index.vue
Ensure there is a `1.5rem` gap between `ActionCard` image and title on small viewport.
- Add margin top to `ActionCard` title on small viewport.
=> Fix Action Card gap between image and title

components/Base/ContactCard/ContactCardChip.vue, components/KenaliCovid/HospitalsAndCallCenters/CallCenters.vue, components/KenaliCovid/HospitalsAndCallCenters/Hospitals.vue, components/KenaliCovid/HospitalsAndCallCenters/Wrapper.vue, components/KenaliCovid/HospitalsAndCallCenters/WrapperItem.vue, components/KenaliCovid/HospitalsAndCallCenters/index.js, components/KenaliCovid/HospitalsAndCallCenters/utils.js, store/call-centers.js, store/hospitals.js
[[Web S6] [Halaman Info Covid-19] Section Ketahui Risiko](https://trello.com/c/B2jmrC73/921-web-s6-halaman-info-covid-19-section-ketahui-risiko)
- `call-centers` and `hospitals` vuex module
- Ensure `options` argument is passed into Firebase query
- `ContactCardChip`
- Add `disabled` state
- Create utilities to map `hospitals` and `call-centers` Firestore collection, in compliance with its corresponding component's props.
- Create views for `hospitals` and `call-centers` data
=> Create hospitals and call centers view

components/SelectInput/index.vue
Preview:
- Event listener on mobile not working because redundant event listener set on input select
Related:
https://airtable.com/appEyAESlNjKaM4we/tbltoI1WyAmGtMSOA/viwYEJD8vBRO53Srp/rec4A23pZn0mBoaO0?blocks=hide
=> delete v-on listener redundant with manual event listener

components/Base/TabLayout/TabLayout.vue
When a carousel lives within a tab layout, but is not set to be the default active tab content, then it would incorrectly compute its sizing.
https://user-images.githubusercontent.com/20709202/133739472-4d9ad7b9-41c9-48a1-addc-3a809d21f6bd.mp4
- `v-show`, a shorthand for `display: none`, is causing that carousel to incorrectly compute its sizing, due to having no information regarding its container width / height.
Use a different approach in toggling between visible tab content item. 
- Replace `v-show` directive with `visibility` CSS attribute
https://user-images.githubusercontent.com/20709202/133739560-2d7c9098-fe26-4dc3-87ab-0e6a8f5c318d.mp4
***
title: Memperbaiki komponen TabLayout
participants: @adrianpdm @ArifWicakSon
=> fix (TabLayout): fix tab content DOM painting, with regard to Carousel;

components/Base/ContentCard/index.vue, pages/index.vue, pages/info/covid-19/index.vue
For page heading, that is the topmost content on each revamped page, title size should be `37px` on desktop/tablet viewport and `28px` on mobile viewport.
Otherwise, use the default `28px` on desktop/tablet viewport and `20px` on mobile viewport.
Adjust content card title styling, with regard to above criteria.
***
title: Perbaikan minor pada komponen dasar untuk tampilan konten
participants: @adrianpdm @maruf_harsono @adzharamrullah @ArifWicakSon @Ibwedagama @bangunbagustapa
=> fix (ContentCard): use different title size for page heading and regular contents

components/AppFooter/index.vue, pages/faq/index.vue, pages/index.vue
1. fix mobile view width button `selengkapnya` on homepage
2. change faq search input placeholder
3. hide faq category section when search input filled
4. fix playstore and appstore footer icon layouting in mobile view
https://trello.com/c/0wKPymFu/958-regression-test-web
title: Fix page revamp layouting
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @bangunbagustapa @yoslie
=> Fix page revamp layouting

components/TabLayout/index.vue, components/_pages/documents/DocumentList.vue, pages/info.vue, pages/info/documents/index.vue, pages/info/infographics/index.vue, store/documents.js, store/infographics.js
1. create search function and component for `info/infographics` and `info/documents`
2. display result count label in `info/infographics` and `info/documents` tabs
[[Web S10] [Informasi > Info Praktikal] Badge pada tab Info Praktikal & Dokumen ketika menampilkan hasil pencarian](https://trello.com/c/fhhJ5DRu/977-web-s10-informasi-info-praktikal-badge-pada-tab-info-praktikal-dokumen-ketika-menampilkan-hasil-pencarian)
title: Infographics and Documents search
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Feat: Infographics and Documents search

api/news.js, pages/articles/index.vue
1. store `search` value on url query
2. remove `content` in `article` search filter property
title: Fix article search bug
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Fix: article search bug

components/AppFooter/index.vue, pages/temp/disclaimer/rdt.vue
1. Remove `Periksa Mandiri` from footer
2. Change tes masif disclaimer redaction
title: Remove Periksa Mandiri from footer
participants: @naufalihsank @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie
=> Hotfix: Remove Periksa Mandiri from footer

pages/info.vue
When user go back from detail page (after info page being filtered previously), the info list is filtered with the search input is null
title: Fix infographics and documents bug
=> Fix: infographics and documents bug

api/news.js, components/Homepage/RecentNewsCarousel/index.vue, components/Vaccine/NewsTabLayout.vue, pages/faq/index.vue
Fix filtering on `faq` and `vaccine` pages
1. [[Web S12][FAQ] FAQ dgn category Vaksin masuk ke dalam tab Covid-19](https://trello.com/c/XrLccXUY/1004-web-s12faq-faq-dgn-category-vaksin-masuk-ke-dalam-tab-covid-19)
2. [[Web S12][Vaksinasi] Berita yg tidak ber tag "vaksin" masuk ke dalam tab Berita Vaksinasi](https://trello.com/c/tuFlUWD2/1003-web-s12vaksinasi-berita-yg-tidak-ber-tag-vaksin-masuk-ke-dalam-tab-berita-vaksinasi)
title: Hotfix items filtering
participants: @naufalihsank @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
=> Hotfix: Items filtering

api/news.js, components/AppDrawer/index.vue, components/Homepage/BannerCarousel/index.vue, components/Homepage/RecentNewsCarousel/index.vue, components/KenaliCovid/HospitalsAndCallCenters/CallCenters.vue, pages/articles/_slug.vue, store/news.js
1. Fix unclickable news in `/vaccine`
2. Fix redirect phone number in `/info/covid-19`
3. Fix unclickable banner in Landing Page
1. [[Web S12][Vaksinasi] Berita yg tidak ber tag "vaksin" masuk ke dalam tab Berita Vaksinasi](https://trello.com/c/tuFlUWD2/1003-web-s12vaksinasi-berita-yg-tidak-ber-tag-vaksin-masuk-ke-dalam-tab-berita-vaksinasi)
2. [[Web S12][Landing Page] Beberapa link tidak bisa diklik](https://trello.com/c/xVmBhvkH/1015-web-s12landing-page-beberapa-link-tidak-bisa-diklik)
3. [[Web S12][Info Covid] Link no Telp di Call Center tidak bisa diklik](https://trello.com/c/SFOhjqtA/1014-web-s12info-covid-link-no-telp-di-call-center-tidak-bisa-diklik)
title: Fix unclickable news
participants: @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama …
=> Hotfix: fix unclickable news

components/_pages/index/VitaminRequest/ConfirmationDetail.vue
**Description**
Mutation `id` district from `int` to `string` must be customized
**Changes**
**Evidence**
title: Fix parse int to handle area id selected
participants: @maulanayuseph @adzharamrullah @naufalihsank @yoslie
=> Fix parse int to handle area id selected

components/_pages/index/VitaminRequest/ConfirmationDetail.vue
**Overview**
Mutation `id` district from `int` to `string` must be customized
**Changes**
**Evidence**
title: Revert area id to string conversion
participants: @maulanayuseph @adzharamrullah
=> Revert area id to string conversion

components/Base/NewsCarousel/NewsCarouselItem.vue, pages/articles/index.vue, pages/index.vue, pages/info.vue, pages/info/covid-19/index.vue, pages/info/documents/index.vue
**Task**
app.clickup.com/t/29p993f
**Changes**
- Add `backlink` to change `URL` link on anti-hoax article
**Preview**
**Evidence**
title: Fix detail anti-hoax article which is doesn't appear
participants: @maulanayuseph @maruf12 @Ibwedagama @agunghide @bangunbagustapa @doohanas
=> Fix detail anti-hoax article which is doesn't appear
